name: calorie_snap
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  camera: ^0.10.5+9
  http: ^1.2.1
  image_picker: ^1.0.7
  path: ^1.8.3
  percent_indicator: ^4.2.2
  provider: ^6.0.3 # 新增這行

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true